module.exports={
    mode:'production',
    entry:{
        path:__dirname+'/src/main.js'
    },
    output:{
        path:__dirname+'/dist',
        filename:'build.js'
    },
    module:{
        rules:[
            {
                test:/\.(jsx|js)$/,
                use:['babel-loader'],
                exclude:/node_modules/
            },
            {
                test:/\.css$/,
                use:['style-loader','css-loader']
            },
            {
                test:/\.(jpg|jpeg|png|gif|woff|svg|ttf|eot|woff2)$/,
                use:['file-loader']
            }
        ]
    },
    plugins:[

    ]
}